//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class deals
    {
        public int Id { get; set; }
        public Nullable<int> Demand_Id { get; set; }
        public Nullable<int> Supply_Id { get; set; }
    
        public virtual Demands Demands { get; set; }
        public virtual supplies supplies { get; set; }
    }
}
